language: bash
services: docker
script:
- docker build -t mydatakeeper/drone-repo-add .
deploy:
  provider: script
  script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    && docker push mydatakeeper/drone-repo-add
  on:
    branch: master
env:
  global:
  - secure: R6QTuofVSu3qsu6aUOdzOadS8cZPmTWb2byDTBjgu94fHDD93hYdP2wK/LcV5HhJcgIsDoWoZZF+mmmT1ruCGO8HE1X1d/P9gAM9MPB+nLjz6At3/PnpEsXbFQbCDFfESYFSvnq+F5wumBXEcy3wWf/x8LusbHyeQihQo/3lJZbclYHmtiK3+xeTuCEqjcmrcZi+g+A2S5lB1O9+FKvI5t0JI0vH/m1fqkhSdJWnsboouXTdaq5v7s5UntC/tM3XyMU4A4h02qh0lGSlfnE+6zAR+Go/dk4pkOHugNobM9OsEI+pu7f96CXMFWbsKJYtGWmMbYg48a2Ro2Ro4qGCekrDC864Kgwa9pC5K2fA+pJ8pepdI83i++fpVhYe3aAI0pdmxHwW+f0nm3mPWSi7aDo0+LG2FPjBR+c2/FTLdCcA4qPLh0vQcrcpSBVfJzRzcm+S49RLICGdJEiLX0lhHBI2xwXIztgCtHujw+f+cuJtohj4Sk+XcpwPHOl8XhpohaY4OynSrk+meqIKT0K5dKlhqrnSNug0dEJhMu+tqhJ57+NzMs3ETv3M3TWcLmH3JJNO0JOfrz0quIql46dqvzU1X2B90wan7jqLPgUuEZ9IsnWMwN4bP712szGY76wafa9QMJRfX2KrQKH4+cY71lesTQNjrsgw6vl0QnamLG4=
  - secure: CGRcDYKYaY8tV5TYGzSO14ivnkTHWxfOsEUComUs6CuI/0JjLpZuP5UWgwUsjEH7V9s9xjAfO4wqKElf58La1wWpNmtd9iiqZ6XJotjjX2iYuEBvwjA0kTTXw7JlZ7FOC7anM8UFKIilV05NJTEBkykBB+3KfZBWl2XCOpI9geY06rsUAq90yHlVEabekQYLHvUE9gBMBUbkMTEGGEZ6lZUiXQOHFIvvmTx+o/QNbG2J0mAbUarHTwF4NqY/uxQRBDHTcvXZ4qiyC/2gOF8dlvN6Z8kFZ/Up3SgyE/MtgbtAN2lwCYUgQAAHkrqSZ/TNn93eugsL4CPREFCtYaJ2D/3ZuNVPQPFkB8sAVoJeKK5wOjBynAIrabr7bsY8+64k8O+NJAff5RUXQOpw0wK046NTL5Ov01hvPqlR0IV+Cyf0h9Y+gt2gOQEhsGVvWBrnFCqBYdTEI8J+0VjQx8wA/GDTQd1DoTtDnLcHyZyRF+njJKw0xFURZacubjPjaFrqmVgnP0Ap4+kB3TLrMMn6dXPiXJrlfZUz5676SIvFvoK0G0/253H8kWHbNHDmdS9RNTgboIqqtKEOMYr0+nX+vE223X1ODEn65fEL1lxHkk/fRdiM+3cU16ucWw5bU6dTy7d+1V8mO1vWZLJireY+bM7DweGhqe7a/+5eFyE+w00=
